// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpaibfzilecqrfhpmnhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwYWliZnppbGVjcXJmaHBtbmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwOTEyMjcsImV4cCI6MjA1MTY2NzIyN30.e8mzuYxZQYI52uSPuKP_IKV_-DTEkGpUdlkB1q05BSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);