// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqjcmzwkjybvqmvjbijo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxamNtendranlidnFtdmpiaWpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNjg5NjcsImV4cCI6MjA1MTc0NDk2N30.L23IkfKOrZR--2dInBEuAzthfc9IYPShf4I6NM79s_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);